apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-routing
  annotations:
    # use the shared ingress-nginx
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: mycredentials
    # nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
spec:
  rules:
  - host: fleetman.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fleetman-webapp
          servicePort: 80
  - host: queue.fleetman.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fleetman-queue
          servicePort: 8161         